spring:
  application:
    name: sms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: whs123!
    url: jdbc:mysql://localhost:3306/cloudDemo?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
env: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
